version: "3"
services:
  front:
    image: seifbarouni/jenkins/front:latest
    ports:
      - 3000:3000
  back:
    image: seifbarouni/jenkins/back:latest
    ports:
      - 9999:9999
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
