version: "3"
services:
  front:
    image: localhost:8082/docker-nexus/front:latest
    ports:
      - 3000:3000
  back:
    image: localhost:8082/docker-nexus/back:latest
    ports:
      - 9999:9999
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
